name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.1.0
        with:
          operations-per-run: 1000
          remove-issue-stale-when-updated: true
          labels-to-remove-when-unstale: 'no-issue-activity,no-pr-activity'
          labels-to-add-when-unstale: 're-opened'
          exempt-all-issue-milestones: true
          exempt-all-pr-milestones: true
          exempt-all-issue-assignees: true
          stale-issue-message: 'This issue is stale because it has been open 120 days with no activity. Remove stale label or comment or this will be closed in 60 days.'
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'awaiting-approval,work-in-progress,dontclose,documentation,security,pinned,future-enhancement,enhancement'
          close-issue-message: 'This issue was closed because it has been stalled for 60 days with no activity.'
          days-before-issue-close: 120
          days-before-issue-stale: 60
          exempt-all-pr-assignees: true
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 30 days with no activity.'
          days-before-pr-stale: 45
          days-before-pr-close: 30
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'awaiting-approval,work-in-progress,dontclose,documentation,security,pinned,future-enhancement,enhancement'
